/**
 * Sprint IMG-1 STEP 3 — hero image prompt markdown files.
 * Shot constraints come from Official HANKKI Hero Style v1.1
 * (`engine/buildHeroPrompt.ts`) — single shared source of truth.
 */
import {
  HANKKI_HERO_STYLE_VERSION,
  HERO_SHOT_REQUIREMENTS,
} from './engine/buildHeroPrompt';
import type { CollectedRecipe } from './types';
import {
  buildSideDishPromptAppend,
  isSideDishRecipe,
  SIDE_DISH_HERO_V2_VERSION,
  SIDE_DISH_SHOT_REQUIREMENTS,
} from './sideDishHeroHints';

function buildPromptParagraphs(recipe: CollectedRecipe): string[] {
  const mains =
    recipe.mainIngredients.length > 0
      ? recipe.mainIngredients.join(', ')
      : 'signature components of the dish';
  const tags =
    recipe.recommendationTags.length > 0
      ? recipe.recommendationTags.join(', ')
      : 'comforting home meal';
  const categories = recipe.category.join(', ');
  const sideDish = isSideDishRecipe(recipe.category);
  const sideAppend = buildSideDishPromptAppend(recipe.heroImageKey, recipe.category);

  if (sideDish) {
    return [
      `Close-up HANKKI mobile hero photograph of ${recipe.recipeTitle} (${recipe.heroImageKey}), a single Korean banchan side dish.`,
      `Cooking style: ${recipe.cookingStyle}. Categories: ${categories}.`,
      `Highlight: ${mains}. Mood tags: ${tags}.`,
      sideAppend,
      `HANKKI Side Dish Hero Style v${SIDE_DISH_HERO_V2_VERSION}. HANKKI Official Hero Style ${HANKKI_HERO_STYLE_VERSION}. Shot requirements: ${SIDE_DISH_SHOT_REQUIREMENTS.join('; ')}.`,
      'Food must look real, fresh, and edible — not glossy 3D or synthetic AI art.',
    ].filter(Boolean);
  }

  const paragraphs = [
    `Close-up HANKKI mobile hero photograph of ${recipe.recipeTitle} (${recipe.heroImageKey}), a finished Korean home-cooked dish.`,
    `Cooking style: ${recipe.cookingStyle}. Categories: ${categories}.`,
    `Highlight main ingredients: ${mains}. Mood tags: ${tags}.`,
    'Main dish is the visual focus: fill 80–92% of the frame; tight mobile crop; camera close; very little or no empty table.',
    'Restaurant-quality Korean food plating; light wooden table; steam naturally visible when appropriate; max one very small side dish; one bowl of rice allowed only if minimal.',
    sideAppend,
    `HANKKI Official Hero Style ${HANKKI_HERO_STYLE_VERSION}. Shot requirements: ${HERO_SHOT_REQUIREMENTS.join('; ')}.`,
    'Food must look real, fresh, and edible — not glossy 3D or synthetic AI art.',
  ].filter(Boolean);

  return paragraphs;
}

export function buildHeroPromptMarkdown(recipe: CollectedRecipe): string {
  const mains =
    recipe.mainIngredients.length > 0
      ? recipe.mainIngredients.join(', ')
      : 'signature components of the dish';
  const tags =
    recipe.recommendationTags.length > 0
      ? recipe.recommendationTags.join(', ')
      : 'comforting home meal';
  const categories = recipe.category.join(', ');

  const lines: string[] = [
    `# Hero Image Prompt — ${recipe.recipeTitle}`,
    '',
    `> Official style: **HANKKI Hero Image Style ${HANKKI_HERO_STYLE_VERSION}**`,
    `> Auto-generated by Hero Image Factory. Do not generate images until human review.`,
    '',
    '## Recipe',
    '',
    `| Field | Value |`,
    `| --- | --- |`,
    `| ID | \`${recipe.id}\` |`,
    `| Title | ${recipe.recipeTitle} |`,
    `| heroImageKey | \`${recipe.heroImageKey}\` |`,
    `| Category | ${categories} |`,
    `| Cooking style | ${recipe.cookingStyle} |`,
    `| Main ingredients | ${mains} |`,
    `| Recommendation tags | ${tags} |`,
    '',
    '## Output',
    '',
    `- Filename: \`${recipe.heroImageKey}.jpg\``,
    `- Prompt file: \`${recipe.heroImageKey}.md\``,
    '',
    '## Prompt',
    '',
    '```',
    buildPromptParagraphs(recipe).join(' '),
    '```',
    '',
    '## Checklist',
    '',
    ...HERO_SHOT_REQUIREMENTS.map((item) => `- [ ] ${item}`),
    '',
  ];

  return lines.join('\n');
}

export function buildHeroPromptBody(recipe: CollectedRecipe): string {
  return buildPromptParagraphs(recipe).join(' ');
}
