import type { ImageSourcePropType } from 'react-native';

/** Keys for bundled local meal images — maps 1:1 to files in `assets/meals/`. */
export type MealLocalAssetKey =
  // Sprint IMG-2 — HANKKI meal keys (alphabetical, on-disk filenames without extension)
  | 'avocado_toast'
  | 'bacon_fried_rice'
  | 'bean_sprout_japchae'
  | 'bean_sprout_muchim'
  | 'bean_sprout_noodle_soup'
  | 'beef_brisket_sukmyeon'
  | 'beef_bulgogi_don'
  | 'beef_jangjorim'
  | 'beef_mushroom_donburi'
  | 'beef_tteokguk'
  | 'bibim_guksu'
  | 'bibim_naengmyeon'
  | 'bibimbap'
  | 'bossam'
  | 'brown_rice_bibimbap'
  | 'budae_jjigae'
  | 'bugeo_guk'
  | 'bulgogi'
  | 'burdock_jorim'
  | 'caesar_salad'
  | 'cheese_ball'
  | 'cheese_egg_rice'
  | 'cheese_ramyeon'
  | 'cheese_sundae_ramyeon'
  | 'cheonggukjang_jjigae'
  | 'cheongyang_tuna_jjigae'
  | 'chicken_breast_donburi'
  | 'chicken_salad'
  | 'chicken_soup'
  | 'chicken_steak'
  | 'chicken_veg_stir_fry_solo'
  | 'club_sandwich'
  | 'cream_pasta'
  | 'cucumber_muchim'
  | 'curry_rice'
  | 'dakbokkeumtang'
  | 'dakgaejang'
  | 'dakgalbi'
  | 'doenjang_guk'
  | 'dried_pollack_bean_sprout_guk'
  | 'dried_pollack_haejang_guk'
  | 'dried_radish_doenjang_guk'
  | 'dried_squid_bokkeum'
  | 'dubu_jorim'
  | 'dwaeji_bulbaek'
  | 'egg_gukbap'
  | 'egg_jangjorim'
  | 'egg_rice'
  | 'egg_roll'
  | 'egg_soup'
  | 'eggplant_donburi'
  | 'eggplant_muchim'
  | 'eungalchi_jorim'
  | 'fish_cake_bokkeum'
  | 'flying_fish_roe_kimchi_rice'
  | 'french_fries'
  | 'french_toast'
  | 'galbitang'
  | 'galchi_jorim'
  | 'gamja_jorim'
  | 'gamjatang'
  | 'garlic_bread_toast_solo'
  | 'garlic_toast'
  | 'gimbap'
  | 'godeungeo_gui'
  | 'godeungeo_jorim'
  | 'goguma_mattang'
  | 'greek_yogurt_bowl'
  | 'green_pepper_tuna_bokkeum'
  | 'haemul_pajeon'
  | 'hamburger'
  | 'honey_glazed_rice_cake'
  | 'hotdog'
  | 'hotteok'
  | 'inari_sushi'
  | 'instant_curry'
  | 'jaeyuk'
  | 'jaeyuk_kimchi_bokkeum'
  | 'janchi_guksu'
  | 'janchi_mandu_guk'
  | 'japchae'
  | 'jjimdak'
  | 'kal_mandu_guk'
  | 'kalguksu'
  | 'kimchi_bokkeum'
  | 'kimchi_fried_rice'
  | 'kimchi_ramyeon'
  | 'kimchi_stew'
  | 'kongnamul_guk'
  | 'konjac_stir_fry'
  | 'lemon_butter_fish'
  | 'lotus_root_jorim'
  | 'meatball'
  | 'microwave_egg_steam'
  | 'microwave_potato'
  | 'microwave_tofu_steam'
  | 'miyeok_chomuchim'
  | 'miyeok_guk'
  | 'myeolchi_bokkeum'
  | 'naengmyeon'
  | 'nakji_bibimbap'
  | 'nakji_bokkeum'
  | 'nut_myeolchi_bokkeum'
  | 'odeng_tang'
  | 'ojingeo_bokkeum'
  | 'omelette'
  | 'omurice'
  | 'osam_bulgogi'
  | 'pad_thai_stir_noodle'
  | 'peanut_butter_toast'
  | 'pepper_potato_jorim'
  | 'pork_cutlet'
  | 'pork_galbi_jjim'
  | 'pot_udon'
  | 'potato_gratin'
  | 'potato_strip_bokkeum'
  | 'quail_egg_jangjorim'
  | 'quinoa_bowl'
  | 'rabokki'
  | 'radish_saengchae'
  | 'ramyeon'
  | 'ramyeon_bokki'
  | 'redbean_toast'
  | 'rose_tteokbokki'
  | 'salmon_poke'
  | 'samgyeopsal_gui'
  | 'saury_soy_jorim'
  | 'sausage_veg_stir_fry'
  | 'shrimp_bokkeum'
  | 'shrimp_fried_rice_solo'
  | 'sogogi_muguk'
  | 'somyeon_jangguk'
  | 'soybean_paste_stew'
  | 'spam_kimchi_fried_rice'
  | 'spicy_bean_sprout_soup'
  | 'spicy_sundae_bokkeum'
  | 'spinach_doenjang_muchim'
  | 'spinach_namul'
  | 'squid_donburi'
  | 'sujebi'
  | 'sukju_namul'
  | 'sundae_bokkeum'
  | 'sundae_guk'
  | 'sundubu_jjigae'
  | 'tofu_gangjeong'
  | 'tofu_kimchi_jjigae_solo'
  | 'tofu_pan_fry'
  | 'tofu_pancake'
  | 'tofu_steak'
  | 'tomato_pasta'
  | 'tteok_mandu_guk'
  | 'tteokbokki'
  | 'tteokgalbi'
  | 'tteokguk'
  | 'tuna_gimbap'
  | 'tuna_kimchi_jjigae'
  | 'tuna_mayo_rice'
  | 'vegetable_soup'
  | 'yukgaejang'
  | 'zucchini_pancake'
  // Legacy fallback key (no hankki-default.png — require points at jaeyuk.jpg)
  | 'hankki-default'
  // Legacy gold_* keys (compatibility; require points at HANKKI/category files)
  | 'gold_kr_kimchi_jjigae'
  | 'gold_kr_samgyeopsal'
  | 'gold_kr_jeyuk_bokkeum'
  | 'gold_kr_bibimbap'
  | 'gold_kr_jjapaghetti'
  | 'gold_j_udon'
  | 'gold_c_jajangmyeon'
  | 'gold_w_cream_pasta'
  | 'category_korean'
  | 'category_japanese'
  | 'category_chinese'
  | 'category_western'
  | 'category_default';

/**
 * Registry entry for a Gold Meal hero image.
 * Set `remoteUrl` when production photography ships — local asset remains fallback.
 */
export type MealImageRegistryEntry = {
  mealId: string;
  emoji: string;
  localAssetKey: MealLocalAssetKey;
  /** Production CDN URL — takes priority over local when set */
  remoteUrl: string | null;
};

export type MealImageSourceType =
  | 'local_asset'
  | 'image_url'
  | 'known_map_local'
  | 'known_map_remote'
  | 'category_fallback'
  | 'placeholder';

export type ResolvedMealImage = {
  emoji: string;
  url?: string | null;
  source?: ImageSourcePropType;
  accessibilityLabel: string;
  /** Dev diagnostics — which resolver branch won */
  sourceType?: MealImageSourceType;
};
