import type { MenuItem } from '../../types/recommendation';
import { attachMenuTags } from './menuCatalogTags';
import { SIDE_DISH_MENUS } from './sideDishCatalog';

const HOMEMADE_MENU_RAW: Omit<MenuItem, 'tags'>[] = [
  {
    id: 'homemade_001',
    mode: 'homemade',
    type: 'MAIN',
    title: '제육볶음',
    subtitle: '20분이면 완성되는 든든한 한 끼',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 20,
    difficulty: 'easy',
    aiReason: '빠르게 만들 수 있고 밥이랑도 잘 어울려요.',
    badges: [
      { label: '⏱ 20분', type: 'time' },
      { label: '🏠 집밥', type: 'family' },
    ],
    honeyTip: '고기는 미리 양념에 재워두면 더 빨리 완성돼요.',
    recommendedSides: ['side_001', 'homemade_016', 'side_003'],
  },
  {
    id: 'homemade_002',
    mode: 'homemade',
    type: 'MAIN',
    title: '된장찌개',
    subtitle: '따뜻한 국물이 생각나는 집밥',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 30,
    difficulty: 'easy',
    aiReason: '따뜻하게 한 그릇 먹기 좋은 날이에요.',
    badges: [
      { label: '⏱ 30분', type: 'time' },
      { label: '🏠 집밥', type: 'family' },
    ],
    honeyTip: '멸치 육수를 쓰면 국물이 훨씬 깊어져요.',
    recommendedSides: ['side_001', 'homemade_016', 'side_002'],
  },
  {
    id: 'homemade_003',
    mode: 'homemade',
    type: 'MAIN',
    title: '김치볶음밥',
    subtitle: '간단하고 든든한 기본 메뉴',
    mealTime: ['LUNCH', 'DINNER', 'LATE_NIGHT'],
    cookTime: 15,
    difficulty: 'easy',
    aiReason: '부담 없이 빠르게 해결하기 좋아요.',
    badges: [{ label: '⏱ 15분', type: 'time' }],
    honeyTip: '마지막에 참기름 한 방울이 포인트예요.',
  },
  {
    id: 'homemade_004',
    mode: 'homemade',
    type: 'MAIN',
    title: '계란토스트',
    subtitle: '아침에 딱 좋은 간단한 한 끼',
    mealTime: ['BREAKFAST'],
    cookTime: 10,
    difficulty: 'easy',
    aiReason: '아침에 부담 없이 든든하게 먹기 좋아요.',
    badges: [
      { label: '⏱ 10분', type: 'time' },
      { label: '☀️ 아침', type: 'season' },
    ],
    honeyTip: '빵에 버터를 바르고 구우면 더 고소해요.',
  },
  {
    id: 'homemade_005',
    mode: 'homemade',
    type: 'MAIN',
    title: '오트밀 바나나볼',
    subtitle: '가볍고 든든한 아침',
    mealTime: ['BREAKFAST'],
    cookTime: 5,
    difficulty: 'easy',
    aiReason: '5분이면 준비 끝, 가볍게 시작하기 좋아요.',
    badges: [{ label: '⏱ 5분', type: 'time' }],
    honeyTip: '전날 밤에 우유에 불려두면 아침이 편해요.',
  },
  {
    id: 'homemade_006',
    mode: 'homemade',
    type: 'MAIN',
    title: '닭가슴살 샐러드',
    subtitle: '가볍고 산뜻한 점심',
    mealTime: ['LUNCH'],
    cookTime: 15,
    difficulty: 'easy',
    aiReason: '점심에 가볍게 먹고 싶을 때 딱이에요.',
    badges: [{ label: '⏱ 15분', type: 'time' }],
    honeyTip: '닭가슴살은 소금·후추만 뿌려 구우면 촉촉해요.',
  },
  {
    id: 'homemade_007',
    mode: 'homemade',
    type: 'MAIN',
    title: '닭볶음탕',
    subtitle: '든든한 저녁 한 상',
    mealTime: ['DINNER'],
    cookTime: 40,
    difficulty: 'normal',
    aiReason: '오늘은 든든하게 먹고 싶을 때 좋아요.',
    badges: [
      { label: '⏱ 40분', type: 'time' },
      { label: '👨‍👩‍👧 가족', type: 'family' },
    ],
    honeyTip: '감자와 당근을 크게 넣으면 더 든든해요.',
    recommendedSides: ['side_002', 'homemade_015', 'side_003'],
  },
  {
    id: 'homemade_008',
    mode: 'homemade',
    type: 'MAIN',
    title: '소고기무국',
    subtitle: '속 편한 따뜻한 국물',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 25,
    difficulty: 'easy',
    aiReason: '따뜻한 국물이 당길 때 좋아요.',
    badges: [{ label: '⏱ 25분', type: 'time' }],
    honeyTip: '소고기를 미리 데치면 국물이 더 맑아요.',
  },
  {
    id: 'homemade_009',
    mode: 'homemade',
    type: 'SIDE',
    title: '계란찜',
    subtitle: '부드럽고 간단한 한 끼',
    mealTime: ['LATE_NIGHT', 'BREAKFAST'],
    cookTime: 10,
    difficulty: 'easy',
    aiReason: '밤에 가볍게 먹기 좋아요.',
    badges: [{ label: '⏱ 10분', type: 'time' }],
    honeyTip: '체에 거른 계란물을 쓰면 더 부드러워요.',
  },
  {
    id: 'homemade_010',
    mode: 'homemade',
    type: 'MAIN',
    title: '간장비빔국수',
    subtitle: '시원하고 간단한 한 그릇',
    mealTime: ['LATE_NIGHT', 'LUNCH'],
    cookTime: 15,
    difficulty: 'easy',
    aiReason: '출출할 때 부담 없이 즐기기 좋아요.',
    badges: [{ label: '⏱ 15분', type: 'time' }],
    honeyTip: '면을 찬물에 헹구면 더 쫄깃해요.',
  },
  {
    id: 'homemade_011',
    mode: 'homemade',
    type: 'MAIN',
    title: '김치전',
    subtitle: '바삭한 간식 겸 한 끼',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 20,
    difficulty: 'easy',
    aiReason: '간단히 구워서 바로 먹기 좋아요.',
    badges: [{ label: '⏱ 20분', type: 'time' }],
    honeyTip: '반죽은 너무 많이 저으면 뻑뻑해져요.',
  },
  {
    id: 'homemade_012',
    mode: 'homemade',
    type: 'MAIN',
    title: '라면 업그레이드',
    subtitle: '계란과 치즈로 한 단계 업',
    mealTime: ['LATE_NIGHT', 'LUNCH'],
    cookTime: 10,
    difficulty: 'easy',
    aiReason: '빠르지만 든든하게 해결하고 싶을 때요.',
    badges: [{ label: '⏱ 10분', type: 'time' }],
    honeyTip: '치즈는 불 끄기 직전에 넣으면 더 쫀득해요.',
  },
  {
    id: 'homemade_013',
    mode: 'homemade',
    type: 'MAIN',
    title: '두부김치',
    subtitle: '집에 있는 재료로 바로',
    mealTime: ['LUNCH', 'DINNER'],
    cookTime: 10,
    difficulty: 'easy',
    aiReason: '재료 걱정 없이 빠르게 먹기 좋아요.',
    badges: [{ label: '⏱ 10분', type: 'time' }],
  },
  {
    id: 'homemade_014',
    mode: 'homemade',
    type: 'MAIN',
    title: '스팸볶음밥',
    subtitle: '든든한 집밥 스타일',
    mealTime: ['LUNCH', 'DINNER', 'LATE_NIGHT'],
    cookTime: 12,
    difficulty: 'easy',
    aiReason: '맛있고 빠르게 한 끼 해결하기 좋아요.',
    badges: [{ label: '⏱ 12분', type: 'time' }],
    honeyTip: '스팸은 먼저 살짝 구우면 고소해요.',
  },
  {
    id: 'homemade_015',
    mode: 'homemade',
    type: 'SIDE',
    title: '감자조림',
    subtitle: '달콤짭짤한 밥도둑',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 25,
    difficulty: 'easy',
    aiReason: '집밥 느낌으로 편하게 먹기 좋아요.',
    badges: [{ label: '⏱ 25분', type: 'time' }],
  },
  {
    id: 'homemade_016',
    mode: 'homemade',
    type: 'SIDE',
    title: '애호박볶음',
    subtitle: '담백한 반찬 겸 한 끼',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 15,
    difficulty: 'easy',
    aiReason: '가볍게 먹고 싶은 날에 잘 어울려요.',
    badges: [{ label: '⏱ 15분', type: 'time' }],
  },
  {
    id: 'homemade_017',
    mode: 'homemade',
    type: 'MAIN',
    title: '참치마요덮밥',
    subtitle: '10분 완성 덮밥',
    mealTime: ['LUNCH', 'DINNER', 'LATE_NIGHT'],
    cookTime: 10,
    difficulty: 'easy',
    aiReason: '빠르고 든든하게 한 그릇 먹기 좋아요.',
    badges: [{ label: '⏱ 10분', type: 'time' }],
    honeyTip: '참기름을 조금 넣으면 고소함이 살아나요.',
  },
  {
    id: 'homemade_018',
    mode: 'homemade',
    type: 'MAIN',
    title: '순두부찌개',
    subtitle: '얼큰하고 따뜻한 한 그릇',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 20,
    difficulty: 'easy',
    aiReason: '오늘은 따뜻한 국물이 땡길 때 좋아요.',
    badges: [{ label: '⏱ 20분', type: 'time' }],
    recommendedSides: ['side_001', 'homemade_016', 'side_004'],
  },
  {
    id: 'homemade_019',
    mode: 'homemade',
    type: 'MAIN',
    title: '불고기',
    subtitle: '달콤한 소고기 집밥',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 25,
    difficulty: 'normal',
    aiReason: '특별한 날처럼 느껴지지만 만들기는 쉬워요.',
    badges: [
      { label: '⏱ 25분', type: 'time' },
      { label: '👨‍👩‍👧 가족', type: 'family' },
    ],
    honeyTip: '양파를 넉넉히 넣으면 더 달큰해요.',
    recommendedSides: ['side_001', 'homemade_016', 'side_002'],
  },
  {
    id: 'homemade_020',
    mode: 'homemade',
    type: 'MAIN',
    title: '카레라이스',
    subtitle: '실패 없는 만만한 메뉴',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 30,
    difficulty: 'easy',
    aiReason: '맛있고 누구나 좋아하는 메뉴예요.',
    badges: [{ label: '⏱ 30분', type: 'time' }],
    honeyTip: '물 대신 우유를 조금 넣으면 부드러워요.',
  },
] ;

export const HOMEMADE_MENUS: MenuItem[] = HOMEMADE_MENU_RAW.map(attachMenuTags);

const DELIVERY_MENU_RAW: Omit<MenuItem, 'tags'>[] = [
  {
    id: 'delivery_001',
    mode: 'delivery',
    type: 'MAIN',
    title: '후라이드 치킨',
    subtitle: '바삭한 클래식 치킨',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 35,
    difficulty: 'easy',
    aiReason: '오늘은 편하게 시켜 먹고 싶을 때 딱이에요.',
    badges: [
      { label: '⏱ 35분', type: 'time' },
      { label: '🚚 배달', type: 'family' },
    ],
    honeyTip: '콜라랑 같이 주문하면 더 시원해요.',
  },
  {
    id: 'delivery_002',
    mode: 'delivery',
    type: 'MAIN',
    title: '양념 치킨',
    subtitle: '달콤매콤한 인기 메뉴',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 35,
    difficulty: 'easy',
    aiReason: '달콤한 맛이 당길 때 좋아요.',
    badges: [{ label: '⏱ 35분', type: 'time' }],
  },
  {
    id: 'delivery_003',
    mode: 'delivery',
    type: 'MAIN',
    title: '족발',
    subtitle: '쫄깃한 야식 대표',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 40,
    difficulty: 'easy',
    aiReason: '든든하게 시켜 먹고 싶은 날에 좋아요.',
    badges: [{ label: '⏱ 40분', type: 'time' }],
    honeyTip: '쌈 채소를 같이 주문하면 더 상큼해요.',
  },
  {
    id: 'delivery_004',
    mode: 'delivery',
    type: 'MAIN',
    title: '보쌈',
    subtitle: '부드러운 수육 한 상',
    mealTime: ['DINNER'],
    cookTime: 40,
    difficulty: 'easy',
    aiReason: '집에서 만들기 번거로울 때 딱이에요.',
    badges: [{ label: '⏱ 40분', type: 'time' }],
  },
  {
    id: 'delivery_005',
    mode: 'delivery',
    type: 'MAIN',
    title: '마르게리타 피자',
    subtitle: '클래식 치즈 피자',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 30,
    difficulty: 'easy',
    aiReason: '간단히 나눠 먹기 좋은 메뉴예요.',
    badges: [{ label: '⏱ 30분', type: 'time' }],
  },
  {
    id: 'delivery_006',
    mode: 'delivery',
    type: 'MAIN',
    title: '불고기 피자',
    subtitle: '한국式 피자 인기 메뉴',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 30,
    difficulty: 'easy',
    aiReason: '맛있게 한 판 해결하기 좋아요.',
    badges: [{ label: '⏱ 30분', type: 'time' }],
  },
  {
    id: 'delivery_007',
    mode: 'delivery',
    type: 'MAIN',
    title: '초밥 세트',
    subtitle: '깔끔한 한 끼',
    mealTime: ['LUNCH', 'DINNER'],
    cookTime: 25,
    difficulty: 'easy',
    aiReason: '가볍지만 만족스럽게 먹기 좋아요.',
    badges: [{ label: '⏱ 25분', type: 'time' }],
    honeyTip: '간장에 와사비를 살짝 넣어보세요.',
  },
  {
    id: 'delivery_008',
    mode: 'delivery',
    type: 'MAIN',
    title: '돈카츠',
    subtitle: '바삭한 일식 돈카츠',
    mealTime: ['LUNCH', 'DINNER'],
    cookTime: 30,
    difficulty: 'easy',
    aiReason: '든든한 한 끼가 필요할 때 좋아요.',
    badges: [{ label: '⏱ 30분', type: 'time' }],
  },
  {
    id: 'delivery_009',
    mode: 'delivery',
    type: 'MAIN',
    title: '짜장면',
    subtitle: '무난하고 맛있는 선택',
    mealTime: ['LUNCH', 'DINNER'],
    cookTime: 25,
    difficulty: 'easy',
    aiReason: '누구나 좋아하는 편안한 맛이에요.',
    badges: [{ label: '⏱ 25분', type: 'time' }],
  },
  {
    id: 'delivery_010',
    mode: 'delivery',
    type: 'MAIN',
    title: '짬뽕',
    subtitle: '얼큰한 국물 면요리',
    mealTime: ['LUNCH', 'DINNER', 'LATE_NIGHT'],
    cookTime: 25,
    difficulty: 'easy',
    aiReason: '오늘은 얼큰한 게 땡길 때 좋아요.',
    badges: [{ label: '⏱ 25분', type: 'time' }],
  },
  {
    id: 'delivery_011',
    mode: 'delivery',
    type: 'MAIN',
    title: '마라탕',
    subtitle: '얼얼한 중식 인기 메뉴',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 30,
    difficulty: 'easy',
    aiReason: '매콤한 맛이 당길 때 잘 어울려요.',
    badges: [{ label: '⏱ 30분', type: 'time' }],
    honeyTip: '순한맛으로 시작해보는 것도 좋아요.',
  },
  {
    id: 'delivery_012',
    mode: 'delivery',
    type: 'MAIN',
    title: '쌀국수',
    subtitle: '담백한 베트남 쌀국수',
    mealTime: ['LUNCH', 'DINNER'],
    cookTime: 25,
    difficulty: 'easy',
    aiReason: '담백하게 먹고 싶을 때 좋아요.',
    badges: [{ label: '⏱ 25분', type: 'time' }],
  },
  {
    id: 'delivery_013',
    mode: 'delivery',
    type: 'MAIN',
    title: '수제버거',
    subtitle: '든든한 버거 세트',
    mealTime: ['LUNCH', 'DINNER'],
    cookTime: 25,
    difficulty: 'easy',
    aiReason: '한 손에 든든하게 먹기 좋아요.',
    badges: [{ label: '⏱ 25분', type: 'time' }],
  },
  {
    id: 'delivery_014',
    mode: 'delivery',
    type: 'MAIN',
    title: '떡볶이',
    subtitle: '매콤달콤 분식 인기',
    mealTime: ['LATE_NIGHT', 'LUNCH'],
    cookTime: 20,
    difficulty: 'easy',
    aiReason: '가볍게 시켜 먹기 좋은 메뉴예요.',
    badges: [{ label: '⏱ 20분', type: 'time' }],
  },
  {
    id: 'delivery_015',
    mode: 'delivery',
    type: 'MAIN',
    title: '김밥',
    subtitle: '간편한 한 줄 식사',
    mealTime: ['BREAKFAST', 'LUNCH'],
    cookTime: 20,
    difficulty: 'easy',
    aiReason: '빠르게 받아서 먹기 좋아요.',
    badges: [{ label: '⏱ 20분', type: 'time' }],
  },
  {
    id: 'delivery_016',
    mode: 'delivery',
    type: 'MAIN',
    title: '샐러드 보울',
    subtitle: '가볍고 산뜻한 한 끼',
    mealTime: ['LUNCH'],
    cookTime: 20,
    difficulty: 'easy',
    aiReason: '점심에 가볍게 먹고 싶을 때요.',
    badges: [{ label: '⏱ 20분', type: 'time' }],
  },
  {
    id: 'delivery_017',
    mode: 'delivery',
    type: 'MAIN',
    title: '크림 파스타',
    subtitle: '부드러운 양식 한 그릇',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 30,
    difficulty: 'easy',
    aiReason: '오늘은 양식이 땡길 때 좋아요.',
    badges: [{ label: '⏱ 30분', type: 'time' }],
  },
  {
    id: 'delivery_018',
    mode: 'delivery',
    type: 'MAIN',
    title: '탕수육',
    subtitle: '바삭달콤 중식 인기',
    mealTime: ['DINNER', 'LUNCH'],
    cookTime: 30,
    difficulty: 'easy',
    aiReason: '맛있게 나눠 먹기 좋은 메뉴예요.',
    badges: [{ label: '⏱ 30분', type: 'time' }],
    honeyTip: '소스는 따로 받으면 더 바삭해요.',
  },
  {
    id: 'delivery_019',
    mode: 'delivery',
    type: 'MAIN',
    title: '곱창볶음',
    subtitle: '쫄깃한 야식 메뉴',
    mealTime: ['DINNER', 'LATE_NIGHT'],
    cookTime: 35,
    difficulty: 'easy',
    aiReason: '오늘은 특별히 시켜 먹고 싶을 때요.',
    badges: [{ label: '⏱ 35분', type: 'time' }],
  },
  {
    id: 'delivery_020',
    mode: 'delivery',
    type: 'MAIN',
    title: '돼지국밥',
    subtitle: '따뜻한 국밥 한 그릇',
    mealTime: ['BREAKFAST', 'LUNCH', 'DINNER', 'LATE_NIGHT'],
    cookTime: 25,
    difficulty: 'easy',
    aiReason: '따뜻하게 한 그릇 먹기 좋아요.',
    badges: [{ label: '⏱ 25분', type: 'time' }],
  },
] ;

export const DELIVERY_MENUS: MenuItem[] = DELIVERY_MENU_RAW.map(attachMenuTags);

export const MENU_CATALOG = {
  homemade: HOMEMADE_MENUS,
  delivery: DELIVERY_MENUS,
  side: SIDE_DISH_MENUS,
} as const;

export function getAllMenus(): MenuItem[] {
  return [...HOMEMADE_MENUS, ...DELIVERY_MENUS, ...SIDE_DISH_MENUS];
}

export function getMenusByMode(mode: MenuItem['mode']): MenuItem[] {
  return MENU_CATALOG[mode];
}
