import { StyleSheet } from 'react-native';
import { ds } from '../../constants/designSystem';

/** Home tokens — Sprint D3-1 premium food experience. */
export const homeRef = {
  colors: {
    surface: ds.colors.card,
    canvas: ds.colors.canvas,
    warmText: ds.colors.warmText,
    track: ds.colors.card,
    chipBg: ds.colors.card,
    badgeBg: ds.colors.badgeBg,
    badgeText: ds.colors.badgeText,
    shadow: ds.colors.shadow,
    glow: ds.colors.glow,
    honeyTipBg: '#FFF9E8',
    reasonBg: ds.colors.reasonBg,
    metaBg: ds.colors.card,
    serviceActiveBg: ds.colors.primary,
    serviceActiveBorder: ds.colors.primary,
    pairingBorder: 'transparent',
    metaDivider: '#EDE6DF',
    honeyBulb: '#F5B800',
    tipBorder: '#F2E6C4',
  },
  card: {
    radius: ds.radius.card,
    borderColor: ds.colors.border,
    paddingH: ds.spacing.cardInner,
    paddingV: ds.spacing.cardInner,
    shadowOffset: ds.shadow.card.shadowOffset,
    shadowOpacity: ds.shadow.card.shadowOpacity,
    shadowRadius: ds.shadow.card.shadowRadius,
    elevation: ds.shadow.card.elevation,
  },
  hero: {
    /** Food hero — wide rectangle (H3); tighter clamp for iPhone CTA (H6) */
    aspectRatio: 1.6,
    minHeight: 188,
    maxHeight: 220,
    imageRadius: ds.radius.image,
  },
  serviceCard: {
    /** Chunky cute service cards — D3-11 */
    height: 92,
    radius: 24,
    background: ds.colors.card,
    borderColor: ds.colors.border,
    accentColor: '#FF8A50',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  spacing: {
    section: ds.spacing.section,
    cardInner: ds.spacing.cardInner,
    actions: ds.spacing.cardInner,
    chip: ds.spacing.cardInner,
  },
  button: {
    height: ds.sizes.buttonHeight,
    radius: ds.radius.button,
    paddingH: ds.spacing.cardInner,
  },
  press: {
    scale: 0.98,
    opacity: 0.97,
  },
} as const;

const cardShadow = {
  ...ds.shadow.card,
  shadowColor: ds.colors.shadow,
};

const softShadow = {
  ...ds.shadow.card,
  shadowColor: ds.colors.shadow,
  shadowOpacity: 0.06,
  shadowRadius: 14,
  elevation: 2,
};

export const homePremiumStyles = StyleSheet.create({
  sectionStack: {
    width: '100%',
    maxWidth: '100%',
    gap: homeRef.spacing.cardInner,
  },
  heroImageStandalone: {
    position: 'relative',
    width: '100%',
    maxWidth: '100%',
    /** Height set at runtime (aspect 1.6, clamped 188–220). */
    borderRadius: homeRef.hero.imageRadius,
    overflow: 'hidden',
    backgroundColor: '#FFE8D4',
    ...cardShadow,
  },
  mealInfoBlock: {
    width: '100%',
    maxWidth: '100%',
    gap: 0,
    paddingTop: 0,
    alignItems: 'flex-start',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'nowrap',
    gap: 10,
    width: '100%',
    maxWidth: '100%',
  },
  mealTitle: {
    ...ds.typography.foodName,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    color: '#3A2417',
    textAlign: 'left',
  },
  warmSentence: {
    ...ds.typography.caption,
    fontWeight: '400',
    color: ds.colors.warmText,
    opacity: 0.9,
    textAlign: 'left',
  },
  recommendationBadge: {
    backgroundColor: ds.colors.badgeBg,
    borderRadius: ds.radius.badge,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 106, 0, 0.18)',
    flexShrink: 0,
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  recommendationBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    color: ds.colors.badgeText,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  /** Kept for TrustReasonChips compatibility (Home uses compact info strip). */
  weatherCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: homeRef.spacing.cardInner,
    backgroundColor: ds.colors.card,
    borderRadius: ds.radius.card,
    paddingVertical: homeRef.spacing.cardInner,
    paddingHorizontal: homeRef.spacing.cardInner,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: ds.colors.borderLight,
    minHeight: 48,
    ...softShadow,
  },
  weatherIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: ds.colors.reasonBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  weatherEmoji: {
    fontSize: 18,
    lineHeight: 22,
  },
  weatherTextBlock: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  weatherTitle: {
    ...ds.typography.caption,
    color: ds.colors.textPrimary,
    fontWeight: '700',
  },
  weatherSubtitle: {
    ...ds.typography.caption,
    fontWeight: '400',
    color: ds.colors.warmText,
  },
  panel: {
    backgroundColor: ds.colors.card,
    borderRadius: ds.radius.card,
    paddingVertical: homeRef.spacing.cardInner,
    paddingHorizontal: homeRef.spacing.cardInner,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: ds.colors.borderLight,
    ...softShadow,
  },
  metaIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  metaText: {
    ...ds.typography.caption,
    color: ds.colors.textSecondary,
    fontWeight: '600',
  },
  pairingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  pairingTitle: {
    ...ds.typography.body,
    fontWeight: '700',
    letterSpacing: -0.2,
    color: ds.colors.textPrimary,
  },
  pairingMore: {
    ...ds.typography.caption,
    color: ds.colors.textMuted,
    fontWeight: '500',
  },
  pairingChip: {
    flex: 1,
    minWidth: 0,
    height: 44,
    borderRadius: ds.radius.chip,
    paddingHorizontal: 8,
    borderWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  pairingChipContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    width: '100%',
  },
  pairingThumb: {
    width: 28,
    height: 28,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: ds.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pairingThumbImage: {
    width: '100%',
    height: '100%',
  },
  pairingChipEmoji: {
    fontSize: 16,
    lineHeight: 20,
  },
  pairingChipText: {
    ...ds.typography.caption,
    fontSize: 12,
    lineHeight: 16,
    color: ds.colors.textPrimary,
    fontWeight: '600',
    textAlign: 'left',
    flexShrink: 1,
  },
  pairingChipRow: {
    flexDirection: 'row',
    gap: homeRef.spacing.cardInner,
    width: '100%',
  },
  honeyTipCard: {
    backgroundColor: homeRef.colors.honeyTipBg,
    borderRadius: ds.radius.card,
    paddingVertical: homeRef.spacing.cardInner,
    paddingHorizontal: homeRef.spacing.cardInner,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: homeRef.colors.tipBorder,
    gap: 6,
  },
  honeyTipHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '100%',
  },
  honeyTipBulbWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  honeyTipTitle: {
    ...ds.typography.caption,
    flex: 1,
    color: ds.colors.textPrimary,
    fontWeight: '700',
  },
  honeyTipBody: {
    ...ds.typography.body,
    fontSize: 15,
    lineHeight: 22,
    color: ds.colors.warmText,
    paddingLeft: 32,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: homeRef.spacing.cardInner,
    width: '100%',
    maxWidth: '100%',
    paddingTop: 0,
  },
  primaryButton: {
    flex: 1,
    minWidth: 0,
    height: homeRef.button.height,
    backgroundColor: ds.colors.primary,
    borderRadius: homeRef.button.radius,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: homeRef.button.paddingH,
    gap: 4,
    ...ds.shadow.button,
  },
  primaryButtonLabel: {
    ...ds.typography.button,
    color: ds.colors.card,
  },
  secondaryButton: {
    flex: 1,
    minWidth: 0,
    height: homeRef.button.height,
    backgroundColor: ds.colors.secondaryButton,
    borderRadius: homeRef.button.radius,
    borderWidth: 1,
    borderColor: ds.colors.secondaryBorder,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: homeRef.button.paddingH,
    gap: 4,
  },
  secondaryButtonLabel: {
    ...ds.typography.button,
    fontWeight: '600',
    color: ds.colors.textSecondary,
  },
});