import type { IngredientAssetEntry, StepAssetEntry } from './types';

const INGREDIENT_STYLE = [
  'Realistic ingredient photography',
  'single ingredient only, centered object',
  'clean neutral cream background',
  'soft natural studio lighting',
  'accurate shape and color',
  'no plate unless necessary',
  'no text, no logo, no watermark, no hands',
  'square composition',
  'consistent product-catalog style',
  'PNG, square, transparent background preferred, otherwise very light cream background',
].join('; ');

const STEP_STYLE = [
  'Realistic Korean home cooking photography',
  'landscape 16:9 composition',
  'warm natural kitchen lighting',
  'simple home cookware',
  'no text, no labels, no logo, no watermark',
  'no unrelated ingredients',
  'food looks realistic, not glossy 3D or AI-rendered',
  'avoid distorted hands; prefer cookware and ingredients as the focus',
].join('; ');

const HERO_STYLE = [
  'Realistic Korean home-cooked meal hero photography',
  'finished dish plated and ready to eat',
  'appetite-appealing, warm natural lighting',
  'simple table or wooden surface, shallow depth of field',
  'no text, no logo, no watermark, no hands',
  'food looks realistic, not glossy 3D or AI-rendered',
  'landscape composition suitable for mobile app meal card',
].join('; ');

export function buildHeroPrompt(input: {
  recipeName: string;
  heroFilename: string;
}): string {
  const key = input.heroFilename.replace(/\.[^.]+$/, '');
  return [
    `Hero photo of ${input.recipeName} (${key}), Korean home cooking.`,
    'Show the completed dish as the clear subject.',
    HERO_STYLE,
  ].join(' ');
}

/** Korean display label for prompts when available. */
function primaryName(names: string[], fallbackKey: string): string {
  return names[0] ?? fallbackKey;
}

export function buildIngredientPrompt(entry: {
  iconKey: string;
  names: string[];
}): string {
  const label = primaryName(entry.names, entry.iconKey);
  return [
    `Photograph of ${label} (${entry.iconKey}), Korean cooking ingredient.`,
    INGREDIENT_STYLE,
  ].join(' ');
}

export function buildStepPrompt(input: {
  recipeName: string;
  order: number;
  title: string;
  instruction: string;
  visibleIngredients: string[];
  notYetIngredients: string[];
}): string {
  const visible =
    input.visibleIngredients.length > 0
      ? input.visibleIngredients.join(', ')
      : 'only items implied by this step';
  const notYet =
    input.notYetIngredients.length > 0
      ? input.notYetIngredients.join(', ')
      : 'none specified';

  return [
    `${input.recipeName} ${input.order}단계: ${input.title}.`,
    input.instruction,
    `Important ingredients visible now: ${visible}.`,
    `What must not appear yet: ${notYet}.`,
    STEP_STYLE,
  ].join(' ');
}

export function formatPromptsMarkdown(
  recipeId: string,
  recipeName: string,
  ingredients: IngredientAssetEntry[],
  steps: StepAssetEntry[],
): string {
  const lines: string[] = [
    `# Recipe asset prompts — ${recipeId} ${recipeName}`,
    '',
    '> Auto-generated by `scripts/recipe-assets`. Human approval required before publishing images.',
    '',
    '## Ingredients',
    '',
  ];

  for (const item of ingredients) {
    lines.push(`### ${item.iconKey} (${item.filename})`);
    lines.push(`- names: ${item.names.join(', ')}`);
    lines.push(`- status: ${item.fileExists ? 'exists' : 'missing'}`);
    lines.push('');
    lines.push('```');
    lines.push(item.prompt);
    lines.push('```');
    lines.push('');
  }

  lines.push('## Cooking steps');
  lines.push('');

  for (const step of steps) {
    lines.push(`### ${step.imageKey} (${step.filename})`);
    lines.push(`- ${step.order}단계: ${step.title}`);
    lines.push(`- status: ${step.fileExists ? 'exists' : 'missing'}`);
    lines.push('');
    lines.push('```');
    lines.push(step.prompt);
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}
