/**
 * Sprint 48-A / 48-B — Convenience combos UI copy.
 */
export const convenienceCombosCopy = {
  title: '편의점 꿀조합',
  description: '든든한 한 끼부터 간식까지, 상황에 맞는 조합을 골라보세요.',
  recommendationDescription:
    '지금 상황에 맞는 조합을 한끼가 먼저 골라드릴게요.',
  todayRecommendationTitle: '오늘의 추천',
  todayRecommendationBadge: '오늘의 추천 ⭐',
  alternateTitle: '이런 조합도 있어요',
  viewAllCombos: '전체 50개 조합 보기',
  eatThisCombo: '이 조합으로 먹기',
  anotherRecommendation: '다른 조합 추천',
  anotherRecommendationDetail: '다른 조합 추천하기',
  allListDescription: '전체 조합을 필터와 정렬로 탐색해 보세요.',
  detailGuideMessage: '이렇게 먹으면 딱이에요!',
  comboPointsTitle: '조합 포인트',
  componentsTitle: '구성품',
  optionalItemBadge: '선택',
  howToMakeTitle: '만드는 방법',
  /** Hero 말풍선 전용 — 짧은 감성 한마디 (10~15자, 상세 설명은 카드 본문). */
  guideDefault: '오늘은 이걸로!',
  situationGuide: {
    hearty: '든든하게 해결!',
    budget: '가성비 최고!',
    lateNight: '야식으로 딱!',
    spicy: '매콤하게 가요!',
    light: '부담 없이!',
    protein: '단백질 챙겨요!',
    dessert: '달달하게!',
    hangover: '속부터 풀어요!',
  },
  countLabel: (count: number) => `등록된 조합 수: ${count}개`,
  resultCount: (count: number) => `${count}개 조합`,
  all: '전체',
  storeCommon: '편의점 공통',
  favorites: '즐겨찾기',
  saved: '저장됨',
  viewCombo: '조합 보기',
  prepTime: '준비 시간',
  estimatedPrice: '예상 가격',
  priceDisclaimer: '상품과 가격은 점포 및 시기에 따라 달라질 수 있어요.',
  emptyFavorites: '저장한 조합이 아직 없어요.',
  emptyFilter: '이 조건에 맞는 조합이 아직 없어요.',
  notFound: '조합을 찾을 수 없어요.',
  notFoundHint: '목록으로 돌아가 다른 조합을 골라보세요.',
  favoritesOnly: '즐겨찾기만',
  sortDefault: '기본',
  sortPriceLow: '가격 낮은 순',
  sortPrepFast: '준비 시간 짧은 순',
  similarTitle: '비슷한 조합',
  assemblyTitle: '이렇게 조합해요',
  calories: '칼로리',
  caloriesUnit: 'kcal',
  difficulty: '난이도',
  itemsTitle: '구성 상품군',
  extraItems: (n: number) => `+${n}`,
  storeCu: 'CU',
  storeGs25: 'GS25',
  storeSeven: '세븐일레븐',
  storeEmart24: '이마트24',
  situation: {
    hearty: '든든한 한 끼',
    budget: '가성비',
    lateNight: '야식',
    spicy: '매운맛',
    light: '가벼운 식사',
    protein: '단백질',
    dessert: '디저트',
    hangover: '해장',
  },
  favoriteAdd: '즐겨찾기에 저장',
  favoriteRemove: '즐겨찾기에서 제거',
  favoriteSaveFailed: '저장에 실패했어요. 다시 시도해 주세요.',
  prepMinutes: (minutes: number) => `${minutes}분`,
  kindFilterAll: '전체',
  kindFilterHack: '진짜 꿀조합',
  kindFilterEasy: '간편 세트',
  kindHackBadge: '꿀조합',
  kindEasyBadge: '간편 세트',
  transformationTitle: '완성되는 메뉴',
  whyItWorksTitle: '왜 맛있는지',
  whyPairingTitle: '함께 먹기 좋은 이유',
  recommendedSituationTitle: '추천 상황',
  assemblyHackHint: '이렇게 섞어보세요',
  assemblyEasyHint: '구성품',
} as const;

export type ConvenienceSituationCopyKey = keyof typeof convenienceCombosCopy.situation;

export type ConvenienceSituationGuideKey = keyof typeof convenienceCombosCopy.situationGuide;

export function getConvenienceSituationGuideMessage(
  situationId: ConvenienceSituationGuideKey,
): string {
  return convenienceCombosCopy.situationGuide[situationId];
}
