/** Logical share-card size. 360×450 at pixelRatio 3 → 1080×1350 (4:5). */
export const WEEKLY_PLAN_SHARE_CARD_WIDTH = 360;
export const WEEKLY_PLAN_SHARE_CARD_HEIGHT = 450;
export const WEEKLY_PLAN_SHARE_PIXEL_RATIO = 3;
export const WEEKLY_PLAN_SHARE_OUTPUT_WIDTH =
  WEEKLY_PLAN_SHARE_CARD_WIDTH * WEEKLY_PLAN_SHARE_PIXEL_RATIO;
export const WEEKLY_PLAN_SHARE_OUTPUT_HEIGHT =
  WEEKLY_PLAN_SHARE_CARD_HEIGHT * WEEKLY_PLAN_SHARE_PIXEL_RATIO;
