/** Sprint 63-C — shopping UI copy (no affiliate / legal text yet). */
export const SHOPPING_COPY = {
  ingredientsCta: '🛒 필요한 재료 장보기',
  ingredientsCtaHint: '선택한 재료의 상품을 찾아드려요',
  missingIngredientsCta: '🛒 부족한 재료 장보기',
  missingIngredientsCtaHint: '없는 재료만 한 번에 찾아봐요',
  missingIngredientsComplete: '지금 있는 재료로 바로 만들 수 있어요',
  checkSeasoningsCta: '+ 양념도 확인하기',
  checkSeasoningsHint: '간장·참기름 등은 집에 있을 수 있어요. 필요하면 선택해 보세요.',
  missingIngredientsCountLabel: (count: number) => `부족한 재료 ${count}개`,
  screenTitleAll: '이 메뉴에 필요한 재료',
  screenTitleMissing: '부족한 재료',
  listHint: '집에 있는 재료는 체크를 해제해 주세요.',
  emptyList: '장보기 항목이 없어요.',
  invalidRecipe: '레시피를 찾을 수 없어요.',
  groupMain: '주재료',
  groupSub: '부재료',
  groupSeasoning: '양념',
  staplesSectionTitle: '기본 양념',
  staplesSectionHint: '집에 보통 있는 재료는 처음에 비활성화돼 있어요.',
  selectedCount: (count: number) => `선택한 재료 ${count}개`,
  purchaseCta: '선택한 재료 상품 보기',
  purchaseCtaPreparing: '상품 연결 준비 중',
  productsSectionTitle: '상품 추천',
  productsDisabled: '상품 연동 준비 중이에요.',
  productsLoading: '상품을 찾는 중…',
  productsEmpty: '추천 상품이 없어요.',
  productsError: '상품을 불러오지 못했어요.',
  productExternalHint: '외부 쇼핑으로 이동',
  productPriceUnavailable: '',
  /** Sprint 66-A — Meal Kit Limited Pilot (HIGH only). */
  mealKitSectionTitle: '간편하게 먹을래요?',
  mealKitSectionBody: '이 메뉴는 밀키트로도 간편하게 준비할 수 있어요.',
  mealKitCta: '밀키트로 간편하게 →',
  mealKitScreenTitle: '밀키트 추천',
  mealKitScreenHint: '바로 조리할 수 있는 밀키트·간편식을 찾아봤어요.',
  mealKitEmpty: '현재 추천 가능한 밀키트가 없어요.',
  mealKitFeatureUnavailable: '밀키트 추천은 준비 중이에요.',
  mealKitProductsTitle: '추천 밀키트',
  prepChoiceShoppingTitle: '필요한 재료 장보기',
  prepChoiceShoppingSubtitle: '직접 만들어 먹어요',
  prepChoiceMealKitTitle: '밀키트로 간편하게',
  prepChoiceMealKitSubtitle: '간편하게 준비해요',
};
