import { ds } from './designSystem';

export const theme = {
  colors: {
    primary: ds.colors.primary,
    primaryDark: ds.colors.primaryDark,
    primarySoft: ds.colors.primarySoft,
    primaryMuted: '#FFE4D4',
    background: ds.colors.card,
    backgroundCream: ds.colors.canvas,
    surface: ds.colors.card,
    card: ds.colors.card,
    bubble: ds.colors.card,
    textPrimary: ds.colors.textPrimary,
    textSecondary: ds.colors.textSecondary,
    textMuted: ds.colors.textMuted,
    border: ds.colors.border,
    borderLight: ds.colors.borderLight,
    borderSubtle: '#FAF4EE',
    success: '#2EBD59',
    warning: '#F4B400',
    error: '#E53935',
    heart: '#FF4757',
    heartInactive: '#D4D4D4',
    splash: ds.colors.canvas,
  },
  typography: {
    headline: { fontSize: 34, fontWeight: '800' as const, letterSpacing: -0.5 },
    greetingTitle: {
      fontSize: ds.typography.pageTitle.fontSize,
      fontWeight: '700' as const,
      lineHeight: ds.typography.pageTitle.lineHeight,
    },
    greetingSubtitle: {
      fontSize: ds.typography.body.fontSize,
      fontWeight: '400' as const,
      lineHeight: ds.typography.body.lineHeight,
    },
    screenTitle: { ...ds.typography.pageTitle },
    cardSectionTitle: {
      fontSize: ds.typography.sectionTitle.fontSize,
      fontWeight: '800' as const,
      lineHeight: ds.typography.sectionTitle.lineHeight,
      letterSpacing: -0.3,
    },
    mealTitle: { ...ds.typography.foodName },
    aiLabel: { fontSize: ds.typography.caption.fontSize, fontWeight: '700' as const },
    menuTitle: { fontSize: 36, fontWeight: '800' as const, letterSpacing: -0.8 },
    menuSubtitle: {
      fontSize: ds.typography.body.fontSize,
      fontWeight: '500' as const,
      lineHeight: ds.typography.body.lineHeight,
    },
    chefMessage: {
      fontSize: ds.typography.body.fontSize,
      fontWeight: '500' as const,
      lineHeight: 26,
    },
    metaText: {
      fontSize: ds.typography.caption.fontSize,
      fontWeight: '600' as const,
    },
    reasonText: {
      fontSize: ds.typography.body.fontSize,
      fontWeight: '400' as const,
      lineHeight: ds.typography.body.lineHeight,
    },
    primaryButton: { ...ds.typography.button },
    secondaryButton: {
      fontSize: ds.typography.button.fontSize,
      fontWeight: '600' as const,
    },
    tipTitle: {
      fontSize: ds.typography.caption.fontSize,
      fontWeight: '700' as const,
    },
    tipBody: {
      fontSize: ds.typography.caption.fontSize,
      fontWeight: '400' as const,
      lineHeight: 21,
    },
    sectionEyebrow: {
      fontSize: 12,
      fontWeight: '600' as const,
      letterSpacing: 0.4,
      lineHeight: 16,
    },
    sectionTitle: { ...ds.typography.sectionTitle },
  },
  radius: {
    card: ds.radius.card,
    heroCard: ds.radius.card,
    image: ds.radius.image,
    button: ds.radius.button,
    badge: ds.radius.badge,
    tip: ds.radius.card,
    bubble: ds.radius.card,
    md: 16,
    lg: ds.radius.card,
    xl: 32,
  },
  spacing: {
    screen: ds.spacing.screen,
    section: ds.spacing.section,
    card: ds.spacing.card,
    cardInner: ds.spacing.cardInner,
    button: ds.spacing.md,
    sm: ds.spacing.sm,
    xs: 16,
    md: ds.spacing.md,
    lg: ds.spacing.lg,
    xl: ds.spacing.xl,
    xxl: ds.spacing.xxl,
  },
  sizes: {
    maxContentWidth: ds.sizes.maxContentWidth,
    primaryButtonHeight: ds.sizes.buttonHeight,
    secondaryButtonHeight: ds.sizes.buttonHeight,
    touchTarget: ds.sizes.touchTarget,
    heroMinHeight: ds.sizes.heroHeight,
  },
  image: {
    heroAspectRatio: 4 / 3,
  },
  interaction: {
    pressed: {
      transform: [{ scale: 0.98 }],
      opacity: 0.95,
    },
    pressedLight: {
      opacity: 0.7,
    },
  },
  shadows: {
    card: ds.shadow.card,
    bubble: ds.shadow.card,
    button: ds.shadow.button,
    tip: ds.shadow.card,
    elevated: ds.shadow.card,
    panel: ds.shadow.card,
  },
};

export type Theme = typeof theme;
